services:
  home-assistant:
    image: homeassistant/home-assistant
    restart: unless-stopped
    volumes:
      - ./hvac_zoning:/config/custom_components/hvac_zoning
      - ./config:/config
    ports:
      - 8123:8123
