services:
  home-assistant:
    image: homeassistant/home-assistant
    restart: unless-stopped
    working_dir: /usr/src/homeassistant
    volumes:
      - ./hvac_zoning:/config/custom_components/hvac_zoning
      - ./hvac_zoning:/usr/src/homeassistant/homeassistant/components/hvac_zoning
      - ./tests:/usr/src/homeassistant/tests
      - ./hvac_stubs:/usr/src/homeassistant/homeassistant/components/hvac_stubs
      - ./configuration.yaml:/config/configuration.yaml
      - ./config:/config
    ports:
      - 8124:8123
